[package]
name = "password-management"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite3 = "0.24.0"
cli-table = "0.4"
dirs = "4.0"
chrono = "0.4"
magic-crypt = "3.1.10"
lazy_static = "1.4.0"